# Generated by Django 5.2.16 on 2026-07-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название заведения')),
                ('slug', models.SlugField(help_text='Идентификатор для QR-кода (например, coffee-place)', unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли очередь')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Номер в очереди')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает'), ('called', 'Вызван'), ('served', 'Обслужен'), ('cancelled', 'Отменил/Не пришел')], default='waiting', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='queue_app.business', verbose_name='Заведение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='queue_app.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись в очереди',
                'verbose_name_plural': 'Записи в очереди',
                'ordering': ['position'],
            },
        ),
    ]
