# Generated by Django 5.2.16 on 2026-07-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_remove_queueitem_business_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальный код для QR (например, my-cafe-1)', unique=True),
        ),
    ]
